--1st QUERY TO RUN IN HISTORY DATABASE FOR ASSIGN SUBJECT TEACHER TO INSERT IN TEACH_SUBJECT TABLE
INSERT INTO "TEACH_SUBJECT" ("FACULTY_ID","SUBJECT_CODE","Batch","DEPARTMENT","SECTION","SEMESTER") VALUES
($1,$2,$3,$4,$5,$6);
--CHANGE IT TO VARIABLE NAMES
--NEXT IN THE BATCH DATABASE, RUN ASSIGN_SUBJECT_BATCH.SQL