--2ND QUERY TO ASSIGN SUBJECT TEACHER IN BATCH DATABASE
INSERT INTO "TEACHING" ("RRN","SUBJECT_CODE","FACULTY_ID")
VALUES($1,$2,$3);
--CHANGE THE VARIABLE NAMES
--IF POSSIBLE,I WILL CHANGE THIS TO COPY COMMAND FOR FASTER INSERTS.
--COPY "TEACHING" FROM stdin WITH DELIMITER ','; 
--130071601097,CSB2104,2000_34