WITH Upd1 as (UPDATE "FACULTY" SET "FACULTY_ADVISOR_BATCH"=$1 WHERE "FACULTY_ID"=$2)--ASSIGNING IN FACULTY TABLE
UPDATE "STUDENT" SET "FACULTY_ADVISOR"=$2 WHERE "DEPARTMENT"=$3 AND "SECTION"=$4--ASSIGNING IN STUDENT TABLE
AND "Batch" = $1 AND "RRN" = ANY ($5);
--CHANGE IT TO VARIABLE NAMES