WITH Upd1 as (UPDATE "FACULTY" SET "FACULTY_ADVISOR_BATCH"=NULL WHERE "FACULTY_ID"=$1)--DEASSIGNING IN FACULTY TABLE. CHANGE IT TO VARIAVLE NAME FOR FACULTY_ID
UPDATE "STUDENT" SET "FACULTY_ADVISOR"=NULL 
WHERE "FACULTY_ADVISOR"=$1;--DEASSIGNING FACULTY ADVISOR USING FACULTY_ID
--CHANGE IT TO VARIABLE NAMES