--2ND QUERY TO RUN AFTER DEASSIGN_SUBJECT_HISTORY.SQL.
--THIS QUERY  DELETES THE RECORD FROM THE  TEACHING TABLE IN BATCH DATABASE.
DELETE FROM "TEACHING" 
USING "STUDENT" 
WHERE "TEACHING"."RRN"= "STUDENT"."RRN"
AND "SUBJECT_CODE"=$2 AND "FACULTY_ID"=$1
AND "DEPARTMENT"=$3 AND "SECTION"=$4;
--CHANGE IT TO VARIABLE NAMES