--1ST QUERY:THIS QUERY DEASSIGNS A SUBJECT TEACHER FROM THE HISTORY DATABASE
DELETE FROM "TEACH_SUBJECT" 
WHERE "FACULTY_ID"=$1 AND "SUBJECT_CODE"=$2 AND "Batch"=$3
AND "DEPARTMENT" = $4 AND "SECTION" =$5--CHANGE IT TO VARIABLE NAMES;
--AFTER THIS RUN DEASSIGN_SUBJ_BATCH.SQL