SELECT "CLASS_ADVISOR","Batch","DEPARTMENT","SECTION"
,COUNT("CLASS_ADVISOR")
FROM "STUDENT" WHERE "CLASS_ADVISOR"=$1--CHANGE IT TO VARIABLE NAME
GROUP BY "CLASS_ADVISOR","Batch","DEPARTMENT","SECTION";