SELECT "CLASS_ADVISOR","Batch","DEPARTMENT","SECTION"
,COUNT("CLASS_ADVISOR"),"SEMESTER"
FROM "STUDENT" INNER JOIN "batch" ON("STUDENT"."Batch"="batch"."BATCH")
WHERE "CLASS_ADVISOR"=$1
GROUP BY "CLASS_ADVISOR","Batch","DEPARTMENT","SECTION","SEMESTER";