--1ST QUERY TO RUN WHEN SHOWING A SUBJECT TEACHER.
SELECT "SUBJECT_CODE","Batch","DEPARTMENT","SECTION","batch"."SEMESTER"
FROM "TEACH_SUBJECT" INNER JOIN "batch" 
ON ("TEACH_SUBJECT"."Batch"= "batch"."BATCH")
WHERE "FACULTY_ID"='2010_34' AND "CURRENT"=TRUE;
