WITH upd1 AS(UPDATE "STUDENT" SET "STUDENT_NAME"=$1,"Batch"=$2 ,"DEPARTMENT"=$4,"SECTION"=$5
WHERE "RRN"=$3)--CHANGE IT TO VARIABLE NAMES
UPDATE "login" SET "DB"=$2--CHANGE IT TO VARIABLE NAMES
WHERE "userid"=$3;--CHANGE IT TO VARIABLE NAMES