SELECT "RRN","STUDENT_NAME","Batch","FACULTY_ID","FACULTY_NAME"
,"FACULTY"."DEPARTMENT","STUDENT"."DEPARTMENT" as "dept","SECTION"
FROM "STUDENT" FULL OUTER JOIN "login" ON "STUDENT"."RRN"="login"."userid"
FULL OUTER JOIN "FACULTY" ON "FACULTY"."FACULTY_ID"="login"."userid"
WHERE "RRN" LIKE $1 OR "STUDENT_NAME" ILIKE $2
OR "FACULTY_ID" ILIKE $3 OR "FACULTY_NAME" ILIKE $4
ORDER BY "RRN"
LIMIT $6 OFFSET $5;