--THIS QUERY IS FOR fromDB TRANSFORMATION  where we give the result of this query to jtrans.js
SELECT DISTINCT ("SUBJECT_CODE") FROM "TEACHING"
INNER JOIN "STUDENT" USING("RRN")
WHERE "CLASS_ADVISOR"='INI101';--CHANGE IT TO FACULTY_ID OF CLASS_ADVISOR
--THE OUTPUT OF THIS QUERY WILL BE
--[{SUBJECT_CODE:"CSB2101"},{"SUBJECT_CODE":"CSB2101"}]
--IT SHOULD BE TRANSFORMED TO
--SUBJECT_CODE:[CSB2101,CSB2102]
--RUN THIS QUERY ALONG WITH CLASSADV_CAT1/CAT2/CAT3/INTERNAL/ENDSEM.SQL