--THIS QUERY IS FOR fromDB TRANSFORMATION  where we give the result of this query to jtrans.js
SELECT "RRN" as rrn,"SUBJECT_CODE" as sub_code ,"CAT1_MARK" as mark,"CAT1_ATTENDANCE" as att
FROM "CAT1_TABLE" INNER JOIN "STUDENT" USING("RRN")
WHERE "CLASS_ADVISOR"=$1 AND "SEM_TAKEN"=$2;
--RUN THIS QUERY PARALLELY ALONG WITH CLASSADV_STU_SUB.SQL