--THIS QUERY UPDATES OR INSERTS FROM CAT1_TEMP_TABLE TO CAT1_TABLE
--HOWEVER THIS WILL NOT WORK FOR CONCURRENT TRANSACTIONS
--FOR CONCURRENT TRANSACTIONS WE HAVE TO USE LOCKS FOR CAT1_TEMP_TABLE
--AND ONLY AFTER TRUNCATE FINISHES, LOCK SHOULD BE RELEASED.
UPDATE "CAT1_TABLE" SET "CAT1_MARK" = "CAT1_TEMP_TABLE"."CAT1_MARK", "CAT1_ATTENDANCE"="CAT1_TEMP_TABLE"."CAT1_ATTENDANCE",
"SEM_TAKEN"="CAT1_TEMP_TABLE"."SEM_TAKEN"
FROM "CAT1_TEMP_TABLE"
WHERE "CAT1_TABLE"."RRN" = "CAT1_TEMP_TABLE"."RRN" AND "CAT1_TABLE"."SUBJECT_CODE"="CAT1_TEMP_TABLE"."SUBJECT_CODE";

INSERT INTO "CAT1_TABLE" ("RRN","SUBJECT_CODE","CAT1_MARK","CAT1_ATTENDANCE","SEM_TAKEN") 
SELECT "CAT1_TEMP_TABLE"."RRN",
"CAT1_TEMP_TABLE"."SUBJECT_CODE",
"CAT1_TEMP_TABLE"."CAT1_MARK",
"CAT1_TEMP_TABLE"."CAT1_ATTENDANCE",
"CAT1_TEMP_TABLE"."SEM_TAKEN"
FROM "CAT1_TEMP_TABLE"
WHERE NOT EXISTS(SELECT"RRN","SUBJECT_CODE","CAT1_MARK","CAT1_ATTENDANCE","SEM_TAKEN" FROM "CAT1_TABLE" WHERE "CAT1_TABLE"."RRN"="CAT1_TEMP_TABLE"."RRN" AND "CAT1_TABLE"."SUBJECT_CODE"="CAT1_TEMP_TABLE"."SUBJECT_CODE");

TRUNCATE "CAT1_TEMP_TABLE";