--1ST QUERY FOR FACULTY ADVISOR IN HISTORY DB GETTING THE DB---------------------
SELECT "FACULTY_ADVISOR_BATCH" AS "DB"
FROM "FACULTY" WHERE "FACULTY_ID" ='2000_33';
--AFTER THIS, RUN faculty_stud.swl------------------