WITH ins1 AS(INSERT INTO "STUDENT" ("RRN","STUDENT_NAME","Batch","DEPARTMENT","SECTION")
VALUES ($1,$2,$3,$6,$7))--CHANGE IT TO VARIABLE NAMES
INSERT INTO "login" VALUES($1,$4,$5,$3);--CHANGE IT TO VARIABLE NAMES