SELECT ROUND(SUM("CREDITS"*"POINTS")/SUM("CREDITS"),1) AS "cgpa" 
FROM "COURSE" INNER JOIN "INTERNALS" USING("RRN","SUBJECT_CODE","SEM_TAKEN")
INNER JOIN "SUBJECT" USING ("SUBJECT_CODE")
INNER JOIN "MARK_SCHEME" USING("GRADE")
WHERE "RRN"=$1 AND "SEM_TAKEN"<=$2;
