SELECT "RRN" ,"CAT1_MARK", "CAT2_MARK", "CAT3_MARK" FROM "CAT1_TABLE"
LEFT OUTER JOIN "CAT2_TABLE" USING ("RRN","SUBJECT_CODE","SEM_TAKEN")
LEFT OUTER JOIN "CAT3_TABLE" USING ("RRN","SUBJECT_CODE","SEM_TAKEN")
WHERE "SUBJECT_CODE"="CSB2101" AND "SEM_TAKEN"=3;