--THIRD QUERY TO RUN FOR SUBJECT TEACHER----------------------
SELECT "SUBJECT_CODE" as sub_code,"SUBJECT_NAME" as sub_name,"CREDITS" as credits
,"CAT1_MARK" as cat1_mark,"CAT1_ATTENDANCE" as cat1_att
,"CAT2_MARK" as cat2_mark,"CAT2_ATTENDANCE" as cat2_att
,"CAT3_MARK" as cat3_mark,"CAT3_ATTENDANCE" as cat3_att
,"INTERNALS" as int_mark,"CUMULATIVE_ATTENDANCE" as cumm_att
,"GRADE" as grade
,"ATTEMPT_ARREAR" as arrear,"ATTEMPT_REDO" as redo
FROM "CAT1_TABLE" LEFT OUTER JOIN "COURSE" USING("RRN","SUBJECT_CODE","SEM_TAKEN")
LEFT OUTER JOIN "CAT2_TABLE" USING("RRN","SUBJECT_CODE","SEM_TAKEN")
LEFT OUTER JOIN "CAT3_TABLE" USING("RRN","SUBJECT_CODE","SEM_TAKEN")
LEFT OUTER JOIN "INTERNALS" USING("RRN","SUBJECT_CODE","SEM_TAKEN")
LEFT OUTER JOIN "SUBJECT" USING ("SUBJECT_CODE")
WHERE "SUBJECT_CODE"='CSB2102' AND "RRN"='130071601097';--CHANGE VARIABLE NAMES