--1ST QUERY TO RUN FOR CLASS ADVISOR IN HISTORY DATABASE TO GET THE DATABASE----------
SELECT "CLASS_ADVISOR_BATCH" AS "DB"
FROM "FACULTY" WHERE "FACULTY_ID" = $1;
--------AFER THIS ,RUN CLASSADV_STU.SQL----------------------